### ISSUE TITLE
Please update your boost libraries to something more current for linux

### ISSUE THREAD

**Issue by mtompkins** [CommerciumBlockchain/Commercium#2]
Precompiled linux wallet uses versions of boost that are old causing:
`error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory`    
Trying to compile directly fails.

**Comment by anthony19114** [comment]
https://packages.ubuntu.com/xenial/libboost-dev
This is the stable version. You can symbolic link whichever version you use.

ln -s /path/to/file /path/to/symlink

To create or update a symlink:

ln -sf /path/to/file /path/to/symlink
